### ISSUE TITLE
Animated webP

### ISSUE THREAD

**Issue by didi789** [facebookincubator/spectrum#44]
There is any way to create animated webp using spectrum?
Something like video to webp / gif to webp / multi png/jpeg/webp to webp?

**Comment by cuva** [comment]
Hi @didi789

Thanks for your interest. Spectrum currently does not handle animated images. My understanding is that it should only process the first still images of an animated webp when decoding and since there’s currently no support for multi frame encoding it would simply transform it into a non animated image.

Hope this helps.

**Comment by didi789** [comment]
Hey cuva, thanks for your reply,
You are planing to add the feature in the future?

https://developers.google.com/speed/webp/docs/webpmux

**Comment by cuva** [comment]
Not that I'm aware for now, but I'll tag @lambdapioneer for further input.

**Comment by lambdapioneer** [comment]
Hi @didi789, 

Currently the Spectrum architecture does not allow for image sequences (such as animated WebP). We also don't plan to change this as the use-case is small with a high cost in terms of change and forward maintenance costs for the project.

For WebP images, you might be able to help yourself though by using Spectrum to encode the individual frames to WebP images. And then you'd (just) need to write a wrapper around the webpmux tools in the webp library which takes those and concatenates them properly. I'm not aware of a easy-to-use project that currently offers this on Android.

As this is a "wont-fix", I'll go ahead and close this issue.
